name: open_car_key_app
description: "Open source car key app."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  dynamic_color: ^1.7.0
  shared_preferences: ^2.5.2
  flutter_blue_plus: ^1.35.3
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  vibration: ^3.1.3
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#423380"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_monochrome: "assets/icon/icon.png"